### ISSUE TITLE
AI Class 025 Feedback

### ISSUE THREAD

**Issue by BaeMinCheon** [CodmingOut/AI_Mentoring#1]
- source : https://github.com/CodmingOut/AI_Mentoring/blob/main/AI_Class/025/README.md

---

Contents | Feedback
--- | ---
`일반 DNN에서` | `기존 DNN에서` 가 적절할 것으로 보임
`CNN에서는 이 이미지의 ~ 것을 목표로 합니다.` | 문맥상 등장하는 이유를 잘 모르겠음. "픽셀화"에 대해 이야기하는 게 아니기 때문
`Convolution은 하나의 이미지로부터 ~ 이미지를 생성하는 것입니다.` | Convolution, 즉 합성곱의 의미를 설명하면서 이러한 수학개념을 활용한 딥러닝 기법이라는 흐름으로 나아가는 것이 자연스러울듯. Convolution 이라는 말이 딥러닝 업계에서만 쓰이는 게 아니고, 이후에도 보게 될 여러 레이어들도 수학개념을 그대로 적용하는 게 아니라 컨셉만 가져오는 경우가 있어 혼동을 줄 수 있음
`필터 갯수 = X 필터 크기 = Y` | 줄바꿈이 안 되어 있어서 혼동을 줌
`필터 1번이 한칸씩 ~ 이미지를 만들게 됩니다.` | 이미지를 어떻게 만드는지에 대한 설명이 없음. 움직이면 도대체 무슨 일이 일어나길래 ?
`padding : 원본 이미지의 ~ 할 수 있습니다.` | 왜 padding 을 추가했을 때 가장자리 부분도 고려할 수 있는지에 대한 설명이 없음
`4. Flatten` | Flatten 의 예시도 있다면 좋겠음. ( Convolution 및 Pooling 은 예시가 있었는데 이건 없길래 )

**Comment by cpprhtn** [comment]
자세한 피드백 감사합니다!!!
반영해보겠습니다.
